### ISSUE TITLE
STMC network  for SLT

### ISSUE THREAD

**Issue by enrico310786** [kayoyin/transformer-slt#11]
Hi, I have read your work carefully and it seems to me well done, congratulations. I am very interested in being able to replicate your results in an end to end manner, and, subsequently, i would like to adapt the work to an Italian Sign Language dataset. Your work is based on two steps, the first is the translation from sign language to glosses through the STMC network. Subsequently, the glosses are translated into text through the transformers. Is there the possibility to share the code regarding the first part in which the STMC network is defined and trained? I'm really interested in the mechanism that takes videos in and translates them into glosses in a continuous way. 

Thanks, Enrico

**Comment by kayoyin** [comment]
Hello! Thank you for your interest and the kind words! Unfortunately, I do not have code for the STMC network that I can share, I would suggest you reach out to the authors of the [STMC model ](https://ojs.aaai.org/index.php/AAAI/article/view/7001) to ask whether they can share the code with you!
