### ISSUE TITLE
Type of SLT Model

### ISSUE THREAD

**Issue by hshreeshail** [kayoyin/transformer-slt#15]
Just wanted to confirm that STMC-Transformer and STMC-RNN are both S2G->G2T models and NOT S2G2T models.
My understanding of these terms is as follows:
S2G->G2T: Where S2G model is trained first, and then, the G2T model is trained on the predictions of the S2G model.
S2G2T: Where S2G & G2T models are trained in a joint manner.
Please correct me if I am wrong.

**Comment by kayoyin** [comment]
Hi! I hope this clarifies things:
S2G->G2T: S2G model is trained first, the G2T model is trained on ground truth glosses (independently of the S2G model) then during inference make predictions conditioned on the output of the S2G model.
S2G2T: S2G model is trained first, then the G2T model is trained using the predictions of the S2G model.

STMC-Transformer and STMC-RNN are both S2G2T models.
