### ISSUE TITLE
Implementation of STMC module ?

### ISSUE THREAD

**Issue by iliasprc** [kayoyin/transformer-slt#2]
Have you implemented the STMC module for tokenization with PyTorch ?

**Comment by sushantMoon** [comment]
Thanks for the hard work @kayoyin, I appreciate it very much. Correct me if I am wrong in my following thoughts.
@IliasPap I think she used the predictions made by STMC directly, i.e. predict gloss with STMC and then use those glosses for translation with the transformer.
She never wrote the whole network (STMC + transformer) was trained end to end (referring to 6.2 section), it was always "train and obtain performance on the glosses predicted by STMC".
