### ISSUE TITLE
The size of the train vocabulary

### ISSUE THREAD

**Issue by NiwakaDev** [kayoyin/transformer-slt#5]
Although the size of the train vocabulary is 1066 In your paper, 
the size of the train vocabulary is 1232 which I built from "phoenix2014T.train.gloss".

Here's the code to find the train vocabulary size.

```

vocab = {}

with open("phoenix2014T.train.gloss", "r") as f:
    lines = f.readlines()

for sentence in lines:
    for word in sentence.strip().split(" "):
        if word in vocab:
            continue
        vocab[word] = len(vocab)
        
print(len(vocab))

```

**Comment by AmitMY** [comment]
And when running `onmt_preprocess` it says 1233 :) 

> * saving 0th train data shard to data/dgs.train.0.pt.   
> * tgt vocab size: 2889. 
>* src vocab size: 1233.
