### ISSUE TITLE
Error in inference (google colab)

### ISSUE THREAD

**Issue by YanSoares** [kayoyin/transformer-slt#8]
First, congratulations on this great job.

I'm trying to replicate your experiments using Google Colab. I managed to do the training, but when I do the inference it triggers an error: RuntimeError: result type Float can't be cast to the desired output type Long

Could you help me with something that can resolve the above error?

Thank you for your attention!
Congratulations again for the work!

**Comment by 1005183361** [comment]
> First, congratulations on this great job.
> 
> I'm trying to replicate your experiments using Google Colab. I managed to do the training, but when I do the inference it triggers an error: RuntimeError: result type Float can't be cast to the desired output type Long
> 
> Could you help me with something that can resolve the above error?
> 
> Thank you for your attention!
> Congratulations again for the work!

Hi！I encountered the same problem, did you solve it？

**Comment by TinoCalamia** [comment]
Same issue for me when replicating!

**Comment by rlhycd** [comment]
Seems that this problem occurs only in newer version of pytorch, for the pytorch 1.6 it seems to work. For the newer one there is some problem with casting to integers, what I've done something like this line https://github.com/kayoyin/transformer-slt/blob/d119fbb642d653a987a2e1b2cd1541c88df7f2ef/onmt/translate/beam_search.py#L190

I've modified
`torch.div(self.topk_ids, vocab_size, out=self._batch_index)
        self._batch_index += self._beam_offset[:_B].unsqueeze(1)`

to a
`out = torch.div(self.topk_ids, vocab_size).long()
        self._batch_index = out + self._beam_offset[:_B].unsqueeze(1)`

And it seems to work.
